# Generated by Django 4.0.1 on 2022-01-31 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_skill_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youtube',
            new_name='social_stackoverflow',
        ),
    ]
