# Generated by Django 4.0.1 on 2022-02-01 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_username_alter_profile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='profile',
            new_name='owner',
        ),
    ]
