# Generated by Django 4.0.1 on 2022-02-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_message_recipient_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='NAME',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
