# Generated by Django 4.0.1 on 2022-02-04 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='NAME',
            new_name='name',
        ),
    ]
