# Generated by Django 4.0.1 on 2022-02-02 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_owner_alter_project_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
