# Generated by Django 4.0.1 on 2022-02-04 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-vote_total']},
        ),
    ]
